openapi: 3.0.0
info:
  title: Items API
  description: API for managing items.
  version: 1.0.0
paths:
  /items:
    get:
      summary: Get all items
      operationId: getItems
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Create a new item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  
  /items/{id}:
    put:
      summary: Update an existing item
      operationId: updateItem
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the item to update
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '204':
          description: Item updated successfully
        '404':
          description: Item not found

    delete:
      summary: Delete an item
      operationId: deleteItem
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the item to delete
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Item deleted successfully
        '404':
          description: Item not found

components:
  schemas:
    Item:
      type: object
      properties:
        Id:
          type: integer
          description: The unique identifier of the item
        Name:
          type: string
          description: The name of the item
      required:
        - Id
        - Name
